from pyspark.sql.types import StructType, StructField, IntegerType, DoubleType, StringType, BooleanType

ENTITIES = {
    "meetings": {
        "table": "local.bronze.meetings",
        "schema": StructType([
            StructField("meeting_key", IntegerType()),
            StructField("meeting_name", StringType()),
            StructField("meeting_official_name", StringType()),
            StructField("location", StringType()),
            StructField("country_key", IntegerType()),
            StructField("country_code", StringType()),
            StructField("country_name", StringType()),
            StructField("country_flag", StringType()),
            StructField("circuit_key", IntegerType()),
            StructField("circuit_short_name", StringType()),
            StructField("circuit_type", StringType()),
            StructField("circuit_info_url", StringType()),
            StructField("circuit_image", StringType()),
            StructField("gmt_offset", StringType()),
            StructField("date_start", StringType()),
            StructField("date_end", StringType()),
            StructField("year", IntegerType()),
            StructField("is_cancelled", BooleanType()),
        ]),
    },
    "drivers": {
        "table": "local.bronze.drivers",
        "schema": StructType([
            StructField("meeting_key", IntegerType()),
            StructField("session_key", IntegerType()),
            StructField("driver_number", IntegerType()),
            StructField("broadcast_name", StringType()),
            StructField("full_name", StringType()),
            StructField("name_acronym", StringType()),
            StructField("team_name", StringType()),
            StructField("team_colour", StringType()),
            StructField("first_name", StringType()),
            StructField("last_name", StringType()),
            StructField("headshot_url", StringType()),
            StructField("country_code", StringType()),
        ]),
    },
    "positions": {
        "table": "local.bronze.positions",
        "schema": StructType([
            StructField("date", StringType()),
            StructField("session_key", IntegerType()),
            StructField("meeting_key", IntegerType()),
            StructField("driver_number", IntegerType()),
            StructField("position", IntegerType()),
        ]),
    },
    "pit_stops": {
        "table": "local.bronze.pit_stops",
        "schema": StructType([
            StructField("date", StringType()),
            StructField("session_key", IntegerType()),
            StructField("lap_number", IntegerType()),
            StructField("lane_duration", DoubleType()),
            StructField("stop_duration", DoubleType()),
            StructField("pit_duration", DoubleType()),
            StructField("meeting_key", IntegerType()),
            StructField("driver_number", IntegerType()),
        ]),
    },
    "stints": {
        "table": "local.bronze.stints",
        "schema": StructType([
            StructField("meeting_key", IntegerType()),
            StructField("session_key", IntegerType()),
            StructField("stint_number", IntegerType()),
            StructField("driver_number", IntegerType()),
            StructField("lap_start", IntegerType()),
            StructField("lap_end", IntegerType()),
            StructField("compound", StringType()),
            StructField("tyre_age_at_start", IntegerType()),
        ]),
    },
    "weather": {
        "table": "local.bronze.weather",
        "schema": StructType([
            StructField("date", StringType()),
            StructField("session_key", IntegerType()),
            StructField("rainfall", DoubleType()),
            StructField("humidity", DoubleType()),
            StructField("air_temperature", DoubleType()),
            StructField("pressure", DoubleType()),
            StructField("wind_direction", IntegerType()),
            StructField("meeting_key", IntegerType()),
            StructField("track_temperature", DoubleType()),
            StructField("wind_speed", DoubleType()),
        ]),
    },
    "race_control": {
        "table": "local.bronze.race_control",
        "schema": StructType([
            StructField("meeting_key", IntegerType()),
            StructField("session_key", IntegerType()),
            StructField("date", StringType()),
            StructField("driver_number", IntegerType()),
            StructField("lap_number", IntegerType()),
            StructField("category", StringType()),
            StructField("flag", StringType()),
            StructField("scope", StringType()),
            StructField("sector", IntegerType()),
            StructField("qualifying_phase", StringType()),
            StructField("message", StringType()),
        ]),
    },
    "team_radio": {
        "table": "local.bronze.team_radio",
        "schema": StructType([
            StructField("meeting_key", IntegerType()),
            StructField("session_key", IntegerType()),
            StructField("driver_number", IntegerType()),
            StructField("date", StringType()),
            StructField("recording_url", StringType()),
        ]),
    },
}